defaults:
- network: uresnet
- framework: tensorflow
- mode: training
- data: real
run:
  distributed: false
  compute_mode: GPU
  iterations: 5608
  minibatch_size: 2
  aux_minibatch_size: ${run.minibatch_size}
  aux_iterations: 10
  id: ???
  precision: float32
  profile: false
  output_dir: output/${framework.name}/${network.name}/${run.id}/
compute_mode:
  minibatch_size: 192
network:
  bias: true
  batch_norm: true
  n_initial_filters: 24
  blocks_per_layer: 3
  blocks_deepest_layer: 5
  blocks_final: 2
  bottleneck_deepest: 152
  residual: true
  downsampling: convolutional
  upsampling: convolutional
  connections: concat
mode:
  optimizer:
    learning_rate: 0.0016020441668120461
    loss_balance_scheme: focal
