defaults:
- network: uresnet
- framework: tensorflow
- mode: training
- data: real
run:
  distributed: false
  compute_mode: GPU
  iterations: 50
  minibatch_size: 2
  aux_minibatch_size: ${run.minibatch_size}
  aux_iterations: 10
  id: ???
  precision: float32
  profile: false
  output_dir: output/${framework.name}/${network.name}/${run.id}/
compute_mode:
  minibatch_size: 128
network:
  bias: false
  batch_norm: true
  n_initial_filters: 8
  blocks_per_layer: 2
  blocks_deepest_layer: 5
  blocks_final: 3
  bottleneck_deepest: 80
  residual: false
  downsampling: max_pooling
  upsampling: interpolation
  connections: concat
mode:
  optimizer:
    learning_rate: 0.001784968104335804
    loss_balance_scheme: light
