defaults:
- network: network0
- framework: tensorflow
- mode: train
- data: real

mode:
  optimizer:
    learning_rate: 0.0005766708795022007
    loss_balance_scheme: none

run:
  distributed: false
  compute_mode: GPU
  iterations: 5608
  aux_minibatch_size: ${run.minibatch_size}
  aux_iterations: 10
  id: ???
  precision: float32
  profile: false
  output_dir: output/${framework.name}/${network.name}/${run.id}/
  minibatch_size: 192
