defaults:
- network: uresnet
- framework: tensorflow
- mode: training
- data: real
run:
  distributed: false
  compute_mode: GPU
  iterations: 50
  minibatch_size: 2
  aux_minibatch_size: ${run.minibatch_size}
  aux_iterations: 10
  id: ???
  precision: float32
  profile: false
  output_dir: output/${framework.name}/${network.name}/${run.id}/
compute_mode:
  minibatch_size: 128
network:
  bias: true
  batch_norm: false
  n_initial_filters: 32
  blocks_per_layer: 2
  blocks_deepest_layer: 4
  blocks_final: 2
  bottleneck_deepest: 152
  residual: true
  downsampling: convolutional
  upsampling: convolutional
  connections: sum
mode:
  optimizer:
    learning_rate: 0.0019951470283041525
    loss_balance_scheme: light
