defaults:
- network: uresnet
- framework: tensorflow
- mode: training
- data: real
run:
  distributed: false
  compute_mode: GPU
  iterations: 8413
  minibatch_size: 2
  aux_minibatch_size: ${run.minibatch_size}
  aux_iterations: 10
  id: ???
  precision: float32
  profile: false
  output_dir: output/${framework.name}/${network.name}/${run.id}/
compute_mode:
  minibatch_size: 128
network:
  bias: false
  batch_norm: false
  n_initial_filters: 32
  blocks_per_layer: 1
  blocks_deepest_layer: 3
  blocks_final: 2
  bottleneck_deepest: 184
  residual: true
  downsampling: max_pooling
  upsampling: convolutional
  connections: concat
mode:
  optimizer:
    learning_rate: 0.002377334852612144
    loss_balance_scheme: focal
