language: python

python:
  - 3.6

os:
  - linux


# This is for the IO layer larcv, and to enable lsf:

before_install:
  - sudo apt-get update
  - sudo apt-get install cmake libhdf5-serial-dev python-dev swig3.0 
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull

install:
  - pip install scikit-build
  # - pip install mpi4py
  - pip install -r requirements.txt
  - echo $PYTHONPATH
  - echo $LD_LIBRARY_PATH
  # - python setup.py install


branchs:
  only:
    - master

script: 
  - pytest tests/
  - mpiexec -n 2 pytest -m distributed_test tests/