# @package _group_
name: default
network_depth: 6
filter_size_deepest: 5
block_concat: False
growth_rate: 1
conv_mode: 2D
data_format: ${data.data_format}
weight_decay: 0.0

bias: true
batch_norm: false
n_initial_filters: 16
blocks_per_layer: 2
blocks_deepest_layer: 4
blocks_final: 3
bottleneck_deepest: 216
residual: false
downsampling: convolutional
upsampling: convolutional
connections: sum
