name: polaris
bias: false
batch_norm: true
n_initial_filters: 16
blocks_per_layer: 2
blocks_deepest_layer: 2
blocks_final: 2
bottleneck_deepest: 96
filter_size_deepest: 5
residual: false
block_concat: False
growth_rate: 1
conv_mode: 2D
network_depth: 7
downsampling: max_pooling
upsampling: interpolation
connections: sum
data_format: ${data.data_format}
weight_decay: 0.0
