
defaults:
  - network: a21
  - framework: tensorflow
  - mode: training
  - data: synthetic
run:
  distributed: False
  compute_mode: GPU
  iterations: 50
  minibatch_size: 2
  aux_minibatch_size: ${minibatch_size}
  aux_iterations: 10
  id: ???

mode.no_summary_images: True

# # Configure the logging and output directory:
hydra:
  job:
    override_dirname: /
  run:
    dir: output/${network.name}/MB${run.minibatch_size}/${hydra:job.override_dirname}
