defaults:
- network: uresnet
- framework: tensorflow
- mode: train
- data: real
run:
  distributed: false
  compute_mode: GPU
  iterations: 5608
  aux_minibatch_size: ${run.minibatch_size}
  aux_iterations: 10
  id: ???
  precision: float32
  profile: false
  output_dir: output/${framework.name}/${network.name}/${run.id}/
  minibatch_size: 192
network:
  bias: true
  batch_norm: false
  n_initial_filters: 16
  blocks_per_layer: 2
  blocks_deepest_layer: 4
  blocks_final: 3
  bottleneck_deepest: 216
  residual: false
  downsampling: convolutional
  upsampling: convolutional
  connections: sum
mode:
  optimizer:
    learning_rate: 0.0005766708795022007
    loss_balance_scheme: none