defaults:
- network: network7
- framework: tensorflow
- mode: train
- data: real
run:
  distributed: true
  compute_mode: GPU
  iterations: 8413
  aux_minibatch_size: ${run.minibatch_size}
  aux_iterations: 10
  id: ???
  precision: float32
  profile: false
  output_dir: output/${framework.name}/${network.name}/${run.id}/
  minibatch_size: 128
mode:
  optimizer:
    learning_rate: 0.002377334852612144
    loss_balance_scheme: focal
