defaults:
- network: uresnet
- framework: tensorflow
- mode: train
- data: real
run:
  distributed: false
  compute_mode: GPU
  iterations: 5608
  aux_minibatch_size: ${run.minibatch_size}
  aux_iterations: 10
  id: ???
  precision: float32
  profile: false
  output_dir: output/${framework.name}/${network.name}/${run.id}/
  minibatch_size: 192
network:
  bias: true
  batch_norm: true
  n_initial_filters: 8
  blocks_per_layer: 3
  blocks_deepest_layer: 2
  blocks_final: 4
  bottleneck_deepest: 88
  residual: true
  downsampling: convolutional
  upsampling: interpolation
  connections: sum
mode:
  optimizer:
    learning_rate: 0.00032480560676946345
    loss_balance_scheme: focal
