defaults:
- network: uresnet
- framework: pytorch
- mode: train
- data: real
data:
  aux_file: none
  downsample: 0
run:
  distributed: true
  iterations: 50
  compute_mode: GPU
  aux_minibatch_size: ${run.minibatch_size}
  aux_iterations: 10
  id: ???
  precision: float32
  profile: false
  output_dir: output/${framework.name}/${network.name}/${run.id}/
  minibatch_size: 4
network:
  bias: false
  batch_norm: true
  n_initial_filters: 16
  blocks_per_layer: 2
  blocks_deepest_layer: 2
  blocks_final: 2
  bottleneck_deepest: 96
  residual: false
  network_depth: 7
  downsampling: max_pooling
  upsampling: interpolation
  connections: sum
mode:
  optimizer:
    loss_balance_scheme: focal
